### ISSUE TITLE
Add Action Logging

### ISSUE THREAD

**Issue by DistroByte** [James-Hackett/DiscordBot#28]
**Is your feature request related to a problem? Please describe.**
When a user joins the server, you can see the join message. However when a user leaves, there is no message. This event would fix that issue

**Describe the solution you'd like**
A message that is only sent when a user leaves the server

Should trigger for:
- [x] leaves
- [x] joins
- [x] kicks
- [x] bans

**Comment by DistroByte** [comment]
@oof2win2 :)

**Comment by oof2win2** [comment]
nice work, that was fast!
